{% set version = "0.2.1" %}

package:
  name: ogh
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/ogh/ogh-{{ version }}.tar.gz
  sha256: 7f39c0416f3733b9a4a1dc90da35ad757726aa65f5c05d1182c8378882806a26

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - setuptools >=38.6.0 
    - wheel >=0.31.0 
    - twine >=1.11.0
  run:
    - python
    - pandas
    - dask
    - descartes
    - geopandas
    - beautifulsoup4
    - basemap
    - python-wget
    - landlab
    - seaborn
    - matplotlib==2.2.3
    - xarray

test:
  imports:
    - ogh

about:
  home: https://github.com/Freshwater-Initiative/Observatory
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for observing the terrestrial and aquatic surfaces of Earth

extra:
  recipe-maintainers:
    - lsetiawan
    - jphuong
    - ocefpaf
