{% set version = "0.1.6a0" %}

package:
  name: ogh
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/ogh/ogh-{{ version }}.tar.gz
  sha256: 4fa735bc1a731ce176627c7180f4cf896a355c394bc3e74a48cd44f420bdf1d6

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pandas
    - dask
    - descartes
    - geopandas
    - beautifulsoup4
    - basemap
    - python-wget

test:
  imports:
    - ogh

about:
  home: https://github.com/Freshwater-Initiative/Observatory
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for observing the terrestrial and aquatic surfaces of Earth

extra:
  recipe-maintainers:
    - lsetiawan
    - jphuong
