{% set version = "0.1.8a0" %}

package:
  name: ogh
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/ogh/ogh-{{ version }}.tar.gz
  sha256: 56f2404b2249316ebb9ea0fa716125ece6518f476bde0342f03d3938343c3fbe

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pandas
    - dask
    - descartes
    - geopandas
    - beautifulsoup4
    - basemap
    - python-wget
    - seaborn
    - basemap-data-hires
    - setuptools>=38.6.0
    - twine>=1.11.0
    - wheel>=0.31.0

test:
  imports:
    - ogh

about:
  home: https://github.com/Freshwater-Initiative/Observatory
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for observing the terrestrial and aquatic surfaces of Earth

extra:
  recipe-maintainers:
    - lsetiawan
    - jphuong
