travis:
  secure:
    BINSTAR_TOKEN: Wru4ao2Of8/LjVYfs+XSEnlgmTtq7ik1iVsqBSQOWT5Sa6kVxZ3H4PRLwwakDMid2b9Yl0Q11sC8rIRlhOqFC9CjodlxIA9ab74IZNijGOuHK+13sPuLWcFdxRBrE8vHMlX0ohe2n+9t9X8TklAl46umziUXjhuRyNHukDxIVJ7mI5nJS0mxTSvJSF4EsuSOmB8wV9FAosPz+R0a6avj2wa7jdeBDZsL60wyPN/LuSYCBBKWvEeDyB0gQz2beEdvbH++MhcbBc4nSd38u1DrWjmQuKMQFrDqZm3gP4wygGk2NiKNvNQcfYUHNPI2T/+19hn62w6dGMiFX9A8D0+keFJnj6bagZEyqkCYtcUmncheGLPF6mMY2dbTtO/xrdIPETGl08SvV8CnmdTkuCrMEGj4qkFyovlYtYKcK3NROTNE0W6hgmSsopFG8Uu0H9WoSSvQG7rAFEAd7ZmtfXAOCHww08CeOwdU0Jb4pGNhh6iR+8/AJgllHLaYGAh17piD37I9XPeFXgzySxXywExKGliIYLaFhmYezoCT51OlmS7qtqOODHTFXJDkTRKhZ/YIvGP+ITFqmDAh6zIXmmADUfTV+t0sX2K0w48wMD+lxNXkMLCsLpf4M6x2gIqAHxH06O34hes0Ss2bBhQOcd+l3Uz2om5TH0DIq6Raqy57/JU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
