travis:
  secure:
    BINSTAR_TOKEN: l6uoNUdZtMFfSJ5w4LoJNT9faPfjJW/WkZX3FmDzoZ/eBiKqeZDCsz0JRsLk4h5DsiWC04hNKMTxyTdhWqZTgmvRSG321Lj9krRI3RSXrscCpJvAv7n+HlBQMwYEWr+3RIVs5sOspya+Sclfdd3YlkT0R68EAIvrsuMoJs1TYiXlMOGKeR/1k/M72JXMqwT8Dc2hldfrGol+rRT4raqZ+c7OUx3YhWYft+ZV4jVkeKNH0x+CWwxXzm6IC4fE9c/HrkMFcvQd2TRSaryZ2peeMebukQ5ES24y+s2GzVA0fRiHjpCXtSa8iBAKbnvcRnw9eHXURBGw83VdD7yDc7rrF+kuIgF52N93WpJhNjRksrXCH778UsMPlnPYtuD/PQGWZJZhRzWDDxFtg/x5sf/mamNKPWGAvpTjhC72tHrR3lUvOAna2Xq7rOCjUKO78ySQFxsR7VUAewZC9RxBctpKQd84Yd/VxnRe57mOsju49NtAm+bFnrxf51JBuC3HyILaTy+Z47jld7VhoSGlY9DPZ0vEmwA6VumlNxsbO9tBx6hkAEPyqKSPMcxDo1MYNtsCfNeQNgKEnqgAadzld84NRGSfr6OFnVSpXAOsKN0NsYz+0BZ+stBnfh8E0hr6YdNnyjJjFIYXgUs2emgDBK6lJF7ETh5Ur3UiouwMlqI+3DQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
